_wandb:
    value:
        cli_version: 0.21.4
        e:
            i8sscdwmn95j62z024tveuhqiszrng6m:
                args:
                    - --config-name
                    - UNet_config.yaml
                codePath: Training_LDM/train.py
                codePathLocal: Training_LDM/train.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "270239182848"
                        used: "7283322880"
                email: shivanshi.asthana@unil.ch
                executable: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/.micromamba/envs/diffscaler/bin/python
                git:
                    commit: a6957b8c5c7b6b5ca8271cdff0748d4bb54ccb36
                    remote: https://github.com/AsthanaShivanshi/Downscaling_Models.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-05c27d52-0d00-690e-8f88-70fd709244b9
                host: dnagpu002
                memory:
                    total: "540478365696"
                os: Linux-5.14.0-427.37.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_LDM/train.py
                python: CPython 3.9.23
                root: .
                slurm:
                    cluster_name: curnagl
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: tbeucler_default
                    job_cpus_per_node: "4"
                    job_end_time: "1757935747"
                    job_gid: "11000"
                    job_gpus: "0"
                    job_id: "55608218"
                    job_name: ckpts_LDM_res_training
                    job_nodelist: dnagpu002
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: gpu-long
                    job_start_time: "1757676547"
                    job_uid: "224526"
                    job_user: sasthana
                    jobid: "55608218"
                    localid: "0"
                    mem_per_node: "262144"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dnagpu002
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models
                    submit_host: curnagl
                    task_pid: "617333"
                    tasks_per_node: "1"
                    topology_addr: core1.edge1.dnagpu002
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=4
                startedAt: "2025-09-12T11:29:14.408154Z"
                writerId: i8sscdwmn95j62z024tveuhqiszrng6m
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 41
                - 50
                - 106
            "2":
                - 1
                - 41
                - 50
                - 106
            "3":
                - 7
                - 66
            "4": 3.9.23
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
