wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.17
    cli_version: 0.20.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752721342
    t:
      1:
      - 1
      - 35
      - 54
      3:
      - 4
      - 13
      - 16
      - 42
      - 55
      4: 3.10.17
      5: 0.20.1
      10:
      - 20
      13: linux-x86_64
optimizer:
  desc: null
  value: Adam
loss:
  desc: null
  value: huber
base_lr:
  desc: null
  value: 0.0001
max_lr:
  desc: null
  value: 0.001
scheduler:
  desc: null
  value: ReduceLROnPlateau
mode:
  desc: null
  value: min
epochs:
  desc: null
  value: 20
optuna_trial:
  desc: null
  value: 27
loss_weights:
  desc: null
  value:
  - 0.3355638091924615
  - 0.22178746765672233
  - 0.20822791543758842
  - 0.23442080771322768
