_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 35
            "2":
                - 1
                - 35
                - 54
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.10.17
            "5": 0.20.1
            "10":
                - 20
            "12": 0.20.1
            "13": linux-x86_64
