_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 54
            "2":
                - 1
                - 54
            "3":
                - 1
                - 13
                - 16
                - 55
            "4": 3.10.17
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
base_lr:
    value: 0.0001
epochs:
    value: 50
loss:
    value: MSE
max_lr:
    value: 0.001
mode:
    value: min
optimizer:
    value: Adam
scheduler:
    value: ReduceLROnPlateau
