experiment:
  batch_size: 32
  num_workers: 4
  quick_test: false #Alternative true would set it into smoke test mode, not for training or inference, just checking everything is alright
# Input channels: [precip, temp, temp_min, temp_max, elevation]
# Output channels: [precip, temp, temp_min, temp_max]
variables:
  input:
    precip: precip
    temp: temp
    temp_min: tmin
    temp_max: tmax
  target:
    precip: precip
    temp: temp
    temp_min: tmin
    temp_max: tmax

preprocessing:
  nan_to_num: true
  nan_value : 0.0


train:
  num_epochs: 100
  checkpoint_path: combined_full_best_model_huber_pretraining_FULL_RLOP.pth
  inference_weights_path: combined_full_best_model_weights_huber_pretraining_FULL_RLOP.pth
  model_config_path: combined_full_model_config_huber_pretraining_FULL_RLOP.json
  in_channels: 5
  out_channels: 4
  optimizer: "Adam"
  #loss_fn: "MSE"
  loss_fn: "huber"
  huber_delta: 0.05

  #scheduler: "CyclicLR"
  #scheduler_mode: "triangular2"
  #base_lr: 1e-4
  #max_lr: 1e-3
  #step_size_up: 208

  #scheduler: "StepLR"
  #gamma: 0.1
  #step_size: 2 #Every 2 epochs, it is reducing the learning rate by 10 percent. Customisable and overridable
   #How was step size chosen? Numer of iterations(training batches) per epoch= len(training_set)/batch_size
  #So following from above, step size up= Number iter per epoch/2

  scheduler: "ReduceLROnPlateau"
  scheduler_mode: "min"
  scheduler_factor: 0.8 #Reducing the learning rate by 20 percent after each patience period
  scheduler_patience: 5 #Waiting for N epochs for no improvement
  early_stopping_patience: 10 #Early stopping patience, if no improvement in validation loss for N epochs, stop training

  wandb_project: "UNet_Deterministic_Combined_Dataset"
  wandb_run_name: "Combined_Full_Huber_UNet_Deterministic"

# Placeholder for the paths in the untracked .paths.yaml file
data: {}
